language: c
before_install:
  - sudo apt-get install libgtk-3-dev
  - make distclean
  - ./configure LIBS="-lm"
  - make
script:
  - cd "src/bin"
  - gcc `pkg-config --cflags gtk+-3.0` -lcrypto -o ../digitalSecurity main.c cmd.c errorHandler.c GUI.c encryption.c converter.c IOHandler.c `pkg-config --libs gtk+-3.0`
